name: Deploy Annor Boutique
on:
  push:
    branches:
      - main
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Recuperation du code
        uses: actions/checkout@v3

      - name: 📂 Synchronisation vers InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_41339234
          password: ${{ secrets.FTP_PASSWORD }}
          # On envoie le contenu du dossier Boutique directement dans htdocs
          local-dir: ./Boutique/
          server-dir: /htdocs/
          # On ignore les fichiers inutiles pour le serveur
          exclude: |
            **/.git*
            **/.github*
